version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: teamtracker_web
    # '/start' is the shell script used to run the service
    command: /app/start.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "teamtrackerdb"
      POSTGRES_USER: "teamtracker"
      POSTGRES_PASSWORD: "teamtracker_password"
    ports:
      - "5432:5432"