# Generated by Django 4.2.6 on 2023-10-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employment_date",
            field=models.DateTimeField(verbose_name="employment date"),
        ),
    ]
